### PR TITLE
Some other small suggestions

### PR DESCRIPTION
**Pull request by cyupa**
Just in case something wasn't clear in the chat :)

### CODE REVIEW

**Comment by jonasborsch** [comment]
Thanks a lot!

**Comment by cyupa** [comment]
You're welcome! I forgot to change `print("StatusCode: \(response.statusCode)")` to  something like`print("\(error)")` in the catch statement. I was jumping between tasks and missed that.

**Comment by jonasborsch** [comment]
Yes I saw that and already fixed it. 😄 Your comment made it clear, that you wanted to use `error`.

Also did some changes and added better error handling. (Didn't commit that yesterday, because I still need to fix some issues).
But in general, a really fun project in which I already learned a lot! 👍

P.S.: Be careful, otherwise I’ll be rivaling your weather app 😎... but that will take much more time 😄

**Comment by cyupa** [comment]
Actually, I'll be doing a re-write of it in the following months, maybe I will make it open source :octocat:

**Pull request merged**
